version: "3.3"
networks:
  elk_net:
services:
  elasticsearch:
    image: "elasticsearch:7.6.0"
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "cluster.name=elasticsearch" # 设置集群名称为elasticsearch
      - "discovery.type=single-node" # 以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 设置使用jvm内存大小
      - "TZ=Asia/Shanghai"
    networks:
      elk_net:
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: "kibana:7.6.0"
    container_name: kibana
    hostname: kibana
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200" # 设置访问elasticsearch的地址
      - "TZ=Asia/Shanghai"
    depends_on:
      - elasticsearch # kibana在elasticsearch启动之后再启动
    networks:
      elk_net:
    ports:
      - "5601:5601"
  logstash:
    image: "logstash:7.6.0"
    container_name: logstash
    hostname: logstash
    environment:
      - "TZ=Asia/Shanghai"
    depends_on:
      - elasticsearch
    networks:
      elk_net:
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
